export const ActionTypes = {
    NEWPOST_SUCCESS: "NEWPOST_SUCCESS",
    NEWPOST_FAIL: "NEWPOST_FAIL",
    GETPOST_SUCCESS: "GETPOST_SUCCESS",
    GETPOST_FAIL: "GETPOST_FAIL",
    NEWCOMMENT_SUCCESS: "NEWCOMMENT_SUCCESS",
    NEWCOMMENT_FAIL: "NEWCOMMENT_FAIL",
    GETCOMMENT_SUCCESS: "GETCOMMENT_SUCCESS",
    GETCOMMENT_FAIL: "GETCOMMENT_FAIL",
}