export const ActionTypes = {
    NEWPOST_SUCCESS: "NEWPOST_SUCCESS",
    NEWPOST_FAIL: "NEWPOST_FAIL",
    GETPOST_SUCCESS: "GETPOST_SUCCESS",
    GETPOST_FAIL: "GETPOST_FAIL",
    NEWCOMMENT_SUCCESS: "NEWCOMMENT_SUCCESS",
    NEWCOMMENT_FAIL: "NEWCOMMENT_FAIL",
    GETCOMMENT_SUCCESS: "GETCOMMENT_SUCCESS",
    GETCOMMENT_FAIL: "GETCOMMENT_FAIL",
    UPDATECOMMENT_SUCCESS: "UPDATECOMMENT_SUCCESS",
    UPDATECOMMENT_FAIL: "UPDATECOMMENT_FAIL",
    DELETECOMMENT_SUCCESS: "DELETECOMMENT_SUCCESS",
    DELETECOMMENT_FAIL: "DELETECOMMENT_FAIL",
    UPDATEPOST_SUCCESS: "UPDATEPOST_SUCCESS",
    UPDATEPOST_FAIL: "UPDATEPOST_FAIL",
    DELETEPOST_SUCCESS: "DELETEPOST_SUCCESS",
    DELETEPOST_FAIL: "DELETEPOST_FAIL"
}